import type { Parameter } from "@/types/parameter";

export const UNIVERSAL_PARAMETERS = [
  {
    id: "legal_name",
    name: "Legal Name",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "short_string",
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Find the registered legal name from an official company page, filing, or corporate registry.",
  },
  {
    id: "common_name",
    name: "Common / Trading Name",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "short_string",
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Use the name the company trades under publicly.",
  },
  {
    id: "founded_year",
    name: "Founded Year",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "number",
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Find the year the company was founded from an official company history, filing, or reliable profile.",
  },
  {
    id: "status",
    name: "Operating Status",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "enum",
    value_schema: { values: ["operating", "acquired", "defunct", "pivoted", "unknown"] },
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Determine whether the company is currently operating, acquired, defunct, pivoted, or unknown.",
  },
  {
    id: "hq_location",
    name: "HQ Location (City, Country)",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "short_string",
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Find the headquarters city and country from an official company page or filing.",
  },
  {
    id: "ownership_type",
    name: "Ownership Type",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "enum",
    value_schema: { values: ["public", "private", "subsidiary", "pe_backed", "government", "unknown"] },
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Identify whether the company is public, private, a subsidiary, PE-backed, government-owned, or unknown.",
  },
  {
    id: "parent_company",
    name: "Parent Company",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "short_string",
    value_schema: { nullable: true },
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "If the company is a subsidiary or brand, identify the parent company; otherwise return null.",
  },
  {
    id: "headcount",
    name: "Headcount (most recent disclosure)",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "object",
    value_schema: { value: "number | string", as_of: "string | null" },
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Find the most recent disclosed employee count and date.",
  },
  {
    id: "annual_revenue",
    name: "Annual Revenue",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "object",
    value_schema: { value: "number | string", currency: "string", fy: "string", source_type: "audited | estimated | reported" },
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "industry_analyst", "news"],
    prompt_hint: "Find the latest annual revenue, fiscal year, currency, and whether the source is audited, estimated, or reported.",
  },
  {
    id: "funding_ma_history",
    name: "Key Funding / M&A Events",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "list",
    value_schema: { item: { date: "string", type: "string", amount: "string | null", counterparty: "string | null" } },
    cell_budget: "paragraph",
    citation_required: true,
    source_preference: ["official_company", "news", "official_third_party"],
    prompt_hint: "Capture major funding, acquisition, merger, or divestiture events relevant to company control and scale.",
  },
  {
    id: "key_leadership",
    name: "Key Leadership (top 2-3)",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "list",
    value_schema: { item: { name: "string", role: "string" } },
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Identify the top 2-3 public leaders most relevant to corporate strategy.",
  },
  {
    id: "primary_urls",
    name: "Public URLs",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "object",
    value_schema: { homepage: "url | null", careers: "url | null", pricing: "url | null", blog: "url | null", press: "url | null", ir: "url | null" },
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company"],
    prompt_hint: "Collect the company's primary public URLs where available.",
  },
  {
    id: "stock_ticker",
    name: "Stock Ticker / Exchange",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "short_string",
    value_schema: { nullable: true },
    cell_budget: "atom",
    citation_required: true,
    source_preference: ["official_third_party", "official_company"],
    prompt_hint: "If public, provide ticker and exchange; otherwise return null.",
  },
  {
    id: "last_valuation",
    name: "Last Known Valuation",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "object",
    value_schema: { value: "number | string | null", currency: "string | null", as_of: "string | null" },
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["news", "official_third_party", "official_company"],
    prompt_hint: "Find the latest public valuation disclosure, if any.",
  },
  {
    id: "latest_material_event",
    name: "Latest Material Event (past 12mo)",
    tier: "universal",
    innovera_dimension: "meta",
    value_type: "object",
    value_schema: { description: "string", date: "string" },
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "news"],
    prompt_hint: "Find the most recent public material event from the past 12 months.",
  },
] as const satisfies readonly Parameter[];

export const FRAMEWORK_PARAMETERS = [
  {
    id: "core_offering",
    name: "Core Product / Service Offering",
    tier: "framework",
    innovera_dimension: "product_solution",
    value_type: "prose",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "industry_analyst"],
    prompt_hint: "Summarize the competitor's core offering using verifiable product or service facts.",
  },
  {
    id: "pipe_or_platform",
    name: "Pipe or Platform",
    tier: "framework",
    innovera_dimension: "product_solution",
    value_type: "enum",
    value_schema: { values: ["pipe", "platform", "hybrid"], include_justification: true },
    cell_budget: "sentence",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Classify as pipe, platform, or hybrid and include a short justification.",
  },
  {
    id: "differentiating_mechanism",
    name: "Key Differentiating Mechanism",
    tier: "framework",
    innovera_dimension: "product_solution",
    value_type: "prose",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "industry_analyst", "news"],
    prompt_hint: "Identify the primary factual mechanism the company claims as differentiation.",
  },
  {
    id: "customer_segment_type",
    name: "Customer Segment Type",
    tier: "framework",
    innovera_dimension: "customers",
    value_type: "enum",
    value_schema: { values: ["B2C", "B2B-SME", "B2B-E", "B2G", "mixed"] },
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Classify the primary customer segment served by the competitor.",
  },
  {
    id: "primary_buyer_persona",
    name: "Primary Buyer Title / Function",
    tier: "framework",
    innovera_dimension: "customers",
    value_type: "short_string",
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Identify the buyer title or function most likely responsible for purchase decisions.",
  },
  {
    id: "customer_concentration",
    name: "Customer Concentration",
    tier: "framework",
    innovera_dimension: "customers",
    value_type: "prose",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Find disclosed concentration facts, named large customers, or public dependency statements.",
  },
  {
    id: "revenue_model",
    name: "Revenue Model",
    tier: "framework",
    innovera_dimension: "transaction",
    value_type: "enum",
    value_schema: { values: ["unit_sales", "subscription", "licensing", "fee_for_service", "commission", "advertising", "rental", "mixed"] },
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Classify how the company primarily monetizes the relevant offering.",
  },
  {
    id: "pricing_disclosure",
    name: "Pricing Disclosure & Tier Range",
    tier: "framework",
    innovera_dimension: "transaction",
    value_type: "object",
    value_schema: { disclosure: "public | partial | opaque", range_low: "number | null", range_high: "number | null", notes: "string" },
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Determine whether pricing is public, partially public, or opaque; capture range where disclosed.",
  },
  {
    id: "margin_profile",
    name: "Margin Profile",
    tier: "framework",
    innovera_dimension: "transaction",
    value_type: "prose",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "industry_analyst", "news", "inferred"],
    prompt_hint: "Use disclosed gross margin if available; otherwise describe only sourced or clearly inferred margin facts.",
  },
  {
    id: "supply_partners",
    name: "Key Supply Partners",
    tier: "framework",
    innovera_dimension: "partners",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "news", "industry_analyst"],
    prompt_hint: "List named suppliers or manufacturing partners where public.",
  },
  {
    id: "distribution_partners",
    name: "Distribution Partners",
    tier: "framework",
    innovera_dimension: "partners",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "news", "official_third_party"],
    prompt_hint: "List named distributors, resellers, integrators, or OEM channel partners.",
  },
  {
    id: "strategic_alliances",
    name: "Strategic Alliances / JVs",
    tier: "framework",
    innovera_dimension: "partners",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "news"],
    prompt_hint: "List strategic alliances, joint ventures, or formal partnerships relevant to the category.",
  },
  {
    id: "gtm_motion",
    name: "Go-to-Market Motion",
    tier: "framework",
    innovera_dimension: "access",
    value_type: "enum",
    value_schema: { values: ["direct_sales", "inside_sales", "channel", "plg", "hybrid"] },
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Classify the primary go-to-market motion for the relevant offering.",
  },
  {
    id: "sales_cycle_length",
    name: "Sales Cycle Length",
    tier: "framework",
    innovera_dimension: "access",
    value_type: "short_string",
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Capture disclosed sales-cycle length, or a brief qualitative estimate if not disclosed.",
  },
  {
    id: "acquisition_channels",
    name: "Primary Acquisition Channels (top 2-3)",
    tier: "framework",
    innovera_dimension: "access",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "List the main customer acquisition channels visible from public information.",
  },
  {
    id: "geographic_footprint",
    name: "Geographic Footprint (sales presence)",
    tier: "framework",
    innovera_dimension: "geography_regulatory",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "Identify regions or countries where the company sells or operates, weighted if disclosed.",
  },
  {
    id: "manufacturing_footprint",
    name: "Manufacturing Footprint",
    tier: "framework",
    innovera_dimension: "geography_regulatory",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "List countries or sites where relevant manufacturing occurs.",
  },
  {
    id: "certifications",
    name: "Industry Certifications & Approvals",
    tier: "framework",
    innovera_dimension: "geography_regulatory",
    value_type: "list",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party"],
    prompt_hint: "List only certifications and approvals relevant to this brief's vertical.",
  },
  {
    id: "capital_intensity",
    name: "Capital Intensity",
    tier: "framework",
    innovera_dimension: "capital_asset",
    value_type: "enum",
    value_schema: { values: ["high", "medium", "low"], include_justification: true },
    cell_budget: "sentence",
    citation_required: false,
    source_preference: ["official_company", "industry_analyst", "inferred"],
    prompt_hint: "Classify capital intensity and justify using public facts about manufacturing, assets, or delivery model.",
  },
  {
    id: "asset_type",
    name: "Primary Asset Type",
    tier: "framework",
    innovera_dimension: "capital_asset",
    value_type: "enum",
    value_schema: { values: ["hardware", "software", "services", "data", "brand", "mixed"] },
    cell_budget: "atom",
    citation_required: false,
    source_preference: ["official_company", "inferred"],
    prompt_hint: "Classify the primary asset type underlying the relevant offering.",
  },
  {
    id: "rd_capacity",
    name: "R&D Capacity (spend / centers / patents)",
    tier: "framework",
    innovera_dimension: "capital_asset",
    value_type: "prose",
    cell_budget: "sentence",
    citation_required: true,
    source_preference: ["official_company", "official_third_party", "news"],
    prompt_hint: "Capture public R&D spend, centers, patents, or equivalent technical-capacity facts.",
  },
] as const satisfies readonly Parameter[];

export const HARDCODED_PARAMETERS = [
  ...UNIVERSAL_PARAMETERS,
  ...FRAMEWORK_PARAMETERS,
] as const satisfies readonly Parameter[];

export function mergeParameterSchema(dynamicParameters: Parameter[]): Parameter[] {
  return [...HARDCODED_PARAMETERS, ...dynamicParameters];
}
